version: 0.0
os: linux
# We need to copy our war file over to the tomcat applications directory, which is /usr/share/tomcat/webapps
files: 
  - source: /target/hello-world-maven.war
    destination: /usr/local/tomcat9/webapps
    overwrite: true

hooks:
# Before the application is deployed, Tomcat needs to be stopped and 
# the existing applications cleaned up
  ApplicationStop:
    - location: scripts/server_stop_clean.sh
      timeout: 60

# Now we can start up Tomcat once again
  ApplicationStart:
    - location: scripts/server_start.sh   
      timeout: 60
